const state={market:"all",q:"",sort_by:"morningstar_gap_pct",sort_order:"desc",page:1,page_size:50,include_unrated:false,include_anomalies:false,total:0};
const $=s=>document.querySelector(s),rows=$("#rows"),terminal=new Set(["success","partial","failed"]);
let activeJob=null,pollTimer=null;
const esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
const val=(v,d=2)=>v==null?"—":Number(v).toFixed(d);
const gap=v=>v==null?'<span class="muted">—</span>':`<span class="${Number(v)>=0?"positive":"negative"}">${Number(v).toFixed(2)}%</span>`;
function syncUrl(){const p=new URLSearchParams();Object.entries(state).forEach(([k,v])=>{if(k!=="total"&&v!==""&&v!==false)p.set(k,v)});history.replaceState(null,"",`${location.pathname}?${p}`)}
function readUrl(){const p=new URLSearchParams(location.search);["market","q","sort_by","sort_order"].forEach(k=>{if(p.has(k))state[k]=p.get(k)});["page","page_size"].forEach(k=>{if(p.has(k))state[k]=Number(p.get(k))});["include_unrated","include_anomalies"].forEach(k=>{if(p.has(k))state[k]=p.get(k)==="true"})}
function quality(i){const s=i.display_quality_status||i.quality_status||"ok",r=i.display_quality_reasons||i.quality_reasons||[];const labels={invalid_price:"价格无效",invalid_target:"目标价无效",extreme_gap:"极端预期差",possible_corporate_action:"公司行动待核",corporate_action_review:"公司行动邻近目标价日期",possible_unadjusted_target:"疑似目标价未复权",single_analyst_extreme_gap:"单一分析师极端值",low_price:"低价股",low_price_extreme_gap:"低价股极端预期差",low_analyst_coverage:"分析师覆盖低",stale_price:"价格过旧",stale_target:"目标价过旧"};return `<span class="quality-tag ${s}" title="${esc(r.map(x=>labels[x]||x).join("；"))}">${s==="ok"?"正常":s==="warning"?"警告":s==="suspicious"?"可疑":"排除"}</span>${r.length?`<small>${esc(r.map(x=>labels[x]||x).join("、"))}</small>`:""}`}
async function load(){syncUrl();rows.innerHTML='<tr><td colspan="13" class="empty-state">加载中…</td></tr>';$("#error").hidden=true;const p=new URLSearchParams(state);p.delete("total");try{const res=await fetch(`/api/expectation-gaps?${p}`,{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);const d=await res.json();state.total=d.total;$("#total-count").textContent=`${d.total} 条`;$("#last-refresh").textContent=`最后更新：${d.last_refresh?.finished_at||"—"}`;$("#page-label").textContent=`第 ${state.page} 页 / 共 ${Math.max(1,Math.ceil(d.total/state.page_size))} 页`;$("#prev").disabled=state.page<=1;$("#next").disabled=state.page*state.page_size>=d.total;if(!d.items.length){rows.innerHTML='<tr><td colspan="13" class="empty-state">没有符合条件的数据</td></tr>';return}rows.innerHTML=d.items.map(i=>`<tr><td><span class="market-tag ${i.market.toLowerCase()}">${i.market==="A"?"A股":"港股"}</span></td><td>${esc(i.symbol)}</td><td class="stock-name">${esc(i.name)}</td><td>${val(i.last_price)}</td><td>${val(i.morningstar_fair_value)}</td><td>${gap(i.morningstar_gap_pct)}</td><td>${i.morningstar_star_rating==null?"—":"★".repeat(i.morningstar_star_rating)} ${i.morningstar_star_rating==null?"":`<span class="rating-tag">${esc(i.rating_label)}</span>`}</td><td>${val(i.analyst_average_target)}</td><td>${gap(i.analyst_gap_pct)}</td><td>${i.analyst_count??"—"}</td><td>${esc(i.data_date||"—")}</td><td><span class="source-tag">${esc(i.display_source)}</span></td><td>${quality(i)}</td></tr>`).join("")}catch(e){$("#error").hidden=false;$("#error").textContent=`加载失败：${e.message}`;rows.innerHTML='<tr><td colspan="13" class="empty-state">数据加载失败</td></tr>'}}
function setButtons(running){document.querySelectorAll("[data-job]").forEach(b=>{b.disabled=running;b.textContent=running?(b.dataset.original||b.textContent)+"（刷新中…）":b.dataset.original});}
function renderJob(j){if(!j||j.status==="never_run")return;activeJob=j;$("#job-status").hidden=false;const names={refresh_a_share:"刷新A股",refresh_hk_prices:"刷新港股股价",refresh_hk_ratings:"刷新港股评级"},states={pending:"等待执行",running:"运行中",success:"成功",partial:"部分成功",failed:"失败"};$("#job-name").textContent=names[j.job_type]||j.job_type;$("#job-state").textContent=states[j.status]||j.status;$("#job-progress").value=j.progress_pct||0;$("#job-counts").textContent=`${j.processed||0} / ${j.total||0}（${Number(j.progress_pct||0).toFixed(2)}%）`;$("#job-results").textContent=`成功 ${j.success_count||0} · 跳过 ${j.skipped_count||0} · 无数据 ${j.no_data_count||0} · 失败 ${j.failure_count||0}`;$("#job-current").textContent=`当前：${j.current_code||"—"}`;$("#job-times").textContent=`开始：${j.started_at||"—"} · 完成：${j.finished_at||"—"}`;$("#job-error").hidden=!j.error_summary;$("#job-error").textContent=j.error_summary||"";setButtons(!terminal.has(j.status));}
async function pollJob(id){clearTimeout(pollTimer);try{const r=await fetch(`/api/refresh-jobs/${id}`,{cache:"no-store"}),j=await r.json();renderJob(j);if(terminal.has(j.status)){await load();return}pollTimer=setTimeout(()=>pollJob(id),2000)}catch(e){$("#job-error").hidden=false;$("#job-error").textContent=`任务状态查询失败：${e.message}`;pollTimer=setTimeout(()=>pollJob(id),2000)}}
async function startJob(kind){const prompt=kind==="hk-ratings"?"全市场评级刷新预计需要约2小时，是否继续？":`确认${kind==="a-share"?"重新导入手工CSV并刷新A股股价": "只刷新全部港股股价"}？`;if(!confirm(prompt))return;setButtons(true);try{const r=await fetch(`/api/refresh-jobs/${kind}`,{method:"POST"}),j=await r.json();if(!r.ok)throw new Error(j.detail||`HTTP ${r.status}`);renderJob(j);pollJob(j.id)}catch(e){setButtons(false);$("#job-status").hidden=false;$("#job-error").hidden=false;$("#job-error").textContent=e.message}}
async function restoreJob(){try{const r=await fetch("/api/refresh-jobs/latest",{cache:"no-store"}),j=await r.json();renderJob(j);if(j.id&&!terminal.has(j.status))pollJob(j.id)}catch(_) {}}
document.querySelectorAll("[data-job]").forEach(b=>{b.dataset.original=b.textContent;b.addEventListener("click",()=>startJob(b.dataset.job))});
let timer;$("#search").addEventListener("input",e=>{clearTimeout(timer);timer=setTimeout(()=>{state.q=e.target.value;state.page=1;load()},300)});$("#market").addEventListener("change",e=>{state.market=e.target.value;state.page=1;load()});["include-unrated","include-anomalies"].forEach(id=>$("#"+id).addEventListener("change",e=>{state[id.replaceAll("-","_")]=e.target.checked;state.page=1;load()}));$("#page-size").addEventListener("change",e=>{state.page_size=Number(e.target.value);state.page=1;load()});$("#reset").addEventListener("click",()=>{Object.assign(state,{market:"all",q:"",sort_by:"morningstar_gap_pct",sort_order:"desc",page:1,page_size:50,include_unrated:false,include_anomalies:false});controls();load()});document.querySelectorAll("[data-sort]").forEach(b=>b.addEventListener("click",()=>{const f=b.dataset.sort;state.sort_order=state.sort_by===f&&state.sort_order==="desc"?"asc":"desc";state.sort_by=f;state.page=1;load()}));$("#prev").onclick=()=>{if(state.page>1){state.page--;load()}};$("#next").onclick=()=>{if(state.page*state.page_size<state.total){state.page++;load()}};function controls(){$("#search").value=state.q;$("#market").value=state.market;$("#include-unrated").checked=state.include_unrated;$("#include-anomalies").checked=state.include_anomalies;$("#page-size").value=String(state.page_size)}readUrl();controls();load();restoreJob();
