(function(root){"use strict";
const DASH="—",STATE={volume_up_price_up:"放量上涨",volume_down_price_up:"缩量上涨",volume_up_price_down:"放量下跌",volume_down_price_down:"缩量下跌",neutral:"平量震荡",history_insufficient:"历史不足"};
function fmt(v,d=2){return v==null?DASH:Number(v).toFixed(d)} function pct(v){return v==null?DASH:`${(Number(v)*100).toFixed(1)}%`} function amount(v){return v==null?DASH:`${(Number(v)/1e8).toFixed(2)}亿`}
function createRadar({document:doc,fetch}){const state={level:2,sort:"score",order:"desc",search:"",items:[],refreshPending:false,poll:null};const by=id=>doc.getElementById(id);const rows=by("sector-rows"),error=by("radar-error"),topScroll=by("industry-scroll-top"),tableWrap=by("industry-table-wrap"),table=doc.querySelector(".industry-table"),refreshText=by("industry-refresh-status"),refreshButton=by("industry-refresh-button");
async function json(url,options){const r=await fetch(url,options);let d;try{d=await r.json()}catch(_){throw Error("服务器返回非 JSON 数据")}if(!r.ok)throw Error(d.detail||`HTTP ${r.status}`);return d}
function cell(tr,text){const td=doc.createElement("td");td.textContent=text;tr.appendChild(td)} function syncScrollWidth(){topScroll.firstElementChild.style.width=`${table.scrollWidth}px`}
function render(){rows.textContent="";if(!state.items.length){const tr=doc.createElement("tr");cell(tr,"暂无本地行业评分数据");tr.firstChild.colSpan=11;rows.appendChild(tr);syncScrollWidth();return}state.items.forEach(x=>{const tr=doc.createElement("tr");tr.tabIndex=0;tr.onclick=()=>detail(x.industry_code);cell(tr,x.industry_name||x.industry_code);cell(tr,x.parent_code||DASH);cell(tr,`${fmt(x.total_score)}/${x.rank_in_level||DASH}`);cell(tr,`${fmt(x.equal_weight_return)}% / ${fmt(x.median_return)}%`);cell(tr,`${pct(x.rise_ratio)} / ${pct(x.strong_rise_ratio)}`);cell(tr,`${x.limit_up_count??DASH} / ${x.first_limit_count??DASH}`);cell(tr,amount(x.turnover_amount));cell(tr,`${fmt(x.turnover_ratio_5d)} / ${fmt(x.turnover_ratio_20d)}`);cell(tr,STATE[x.price_volume_state]||x.price_volume_state||DASH);cell(tr,pct(x.coverage_ratio));cell(tr,x.confidence||DASH);rows.appendChild(tr)});syncScrollWidth()}
async function load(){try{error.hidden=true;const q=new URLSearchParams({level:state.level,sort_by:state.sort,order:state.order,page_size:200,search:state.search});const d=await json(`/api/industry/list?${q}`);state.items=d.items;by("industry-trade-date").textContent=d.trade_date||DASH;render()}catch(e){error.textContent=e.message;error.hidden=false;state.items=[];render()}}
async function detail(code){try{const d=await json(`/api/industry/detail?industry_code=${encodeURIComponent(code)}`);const s=d.score||{},p=d.snapshot||{};by("detail-content").textContent=`${d.node.industry_name}\n综合评分 ${fmt(s.total_score)}，同层排名 ${s.rank_in_level||DASH}/${s.industry_count_in_level||DASH}\n强度 ${fmt(s.strength_score)}　广度 ${fmt(s.breadth_score)}　强势上涨 ${fmt(s.strong_rise_score)}　涨停联动 ${fmt(s.limit_score)}　量价 ${fmt(s.activity_score)}　持续性 ${fmt(s.persistence_score)}　质量 ${fmt(s.quality_score)}\n量价状态：${STATE[s.price_volume_state]||DASH}；覆盖率：${pct(p.coverage_ratio)}\n父行业：${d.parent?.industry_name||DASH}；子行业：${d.children.map(x=>x.industry_name).join("、")||DASH}`;by("industry-detail").showModal()}catch(e){error.textContent=e.message;error.hidden=false}}
function showStatus(s){const missing=(s.missing_trade_dates||[]).length;if(s.is_running){refreshText.textContent=`正在补齐${missing?`${missing}个缺失交易日`:'板块数据'}…`;refreshButton.disabled=true;refreshButton.textContent="补齐中…";return}refreshButton.disabled=false;if(s.run_status==="failed"||s.run_status==="partial_success"){refreshText.textContent=`补齐失败：${s.last_error||'后台任务未完成'}`;refreshButton.textContent="重试补齐"}else if(s.is_latest){refreshText.textContent=`板块数据：最新；目标交易日：${s.target_trade_date||DASH}`;refreshButton.textContent="已是最新"}else if(s.calendar_error){refreshText.textContent=`无法判断交易日：${s.calendar_error}`;refreshButton.textContent="重试同步"}else{refreshText.textContent=`板块数据落后 ${missing} 个交易日；目标：${s.target_trade_date||DASH}`;refreshButton.textContent=missing>1?`补齐${missing}个交易日`:`同步到${s.target_trade_date||'最新交易日'}`}}
async function checkRefresh(){try{const s=await json("/api/industry/refresh-status");showStatus(s);if(s.is_running){if(state.poll)clearTimeout(state.poll);state.poll=setTimeout(checkRefresh,1200);return}if(state.refreshPending){state.refreshPending=false;if(s.is_latest){refreshText.textContent="补齐完成";await load()}else if(s.run_status!=="failed"&&s.run_status!=="partial_success"){refreshText.textContent="补齐完成，但数据仍未达到最新状态"}}}catch(e){state.refreshPending=false;refreshText.textContent=`同步状态检查失败：${e.message}`;refreshButton.disabled=false;refreshButton.textContent="重试补齐"}}
async function triggerRefresh(){if(refreshButton.disabled)return;state.refreshPending=true;refreshButton.disabled=true;refreshButton.textContent="补齐中…";refreshText.textContent="正在提交补齐任务…";try{const d=await json("/api/industry/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(d.status==="accepted"||d.status==="already_running"){state.poll=setTimeout(checkRefresh,500)}else{state.refreshPending=false;showStatus(d)}}catch(e){state.refreshPending=false;refreshText.textContent=`同步失败：${e.message}`;refreshButton.disabled=false;refreshButton.textContent="重试补齐"}}
topScroll.onscroll=()=>{tableWrap.scrollLeft=topScroll.scrollLeft};tableWrap.onscroll=()=>{topScroll.scrollLeft=tableWrap.scrollLeft};if(root.addEventListener)root.addEventListener("resize",syncScrollWidth);doc.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{doc.querySelectorAll("[data-level]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.level=Number(b.dataset.level);load()});by("industry-search").oninput=e=>{state.search=e.target.value;load()};by("industry-sort").onchange=e=>{state.sort=e.target.value;load()};by("industry-order").onclick=()=>{state.order=state.order==="desc"?"asc":"desc";by("industry-order").textContent=state.order==="desc"?"降序":"升序";load()};by("detail-close").onclick=()=>by("industry-detail").close();refreshButton.onclick=triggerRefresh;return{state,load,render,detail,checkRefresh,triggerRefresh}}
if(typeof module!=="undefined")module.exports={createRadar,fmt,pct,amount};else{const radar=createRadar({document:root.document,fetch:root.fetch.bind(root)});radar.load();radar.checkRefresh()}})(typeof window!=="undefined"?window:globalThis);
