CREATE TABLE IF NOT EXISTS sector_breadth_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    classification_system TEXT NOT NULL,
    sector_code TEXT NOT NULL,
    trade_date TEXT NOT NULL,
    membership_snapshot_date TEXT NOT NULL,
    above_ma5_ratio REAL,
    above_ma5_numerator INTEGER NOT NULL DEFAULT 0,
    above_ma5_valid_count INTEGER NOT NULL DEFAULT 0,
    above_ma10_ratio REAL,
    above_ma10_numerator INTEGER NOT NULL DEFAULT 0,
    above_ma10_valid_count INTEGER NOT NULL DEFAULT 0,
    above_ma20_ratio REAL,
    above_ma20_numerator INTEGER NOT NULL DEFAULT 0,
    above_ma20_valid_count INTEGER NOT NULL DEFAULT 0,
    advancing_ratio REAL,
    advancing_numerator INTEGER NOT NULL DEFAULT 0,
    advancing_valid_count INTEGER NOT NULL DEFAULT 0,
    new_high_20_ratio REAL,
    new_high_20_numerator INTEGER NOT NULL DEFAULT 0,
    new_high_20_valid_count INTEGER NOT NULL DEFAULT 0,
    volume_expansion_ratio REAL,
    volume_expansion_numerator INTEGER NOT NULL DEFAULT 0,
    volume_expansion_valid_count INTEGER NOT NULL DEFAULT 0,
    total_members INTEGER NOT NULL CHECK(total_members >= 0),
    valid_members INTEGER NOT NULL CHECK(valid_members >= 0),
    coverage_ratio REAL NOT NULL CHECK(coverage_ratio BETWEEN 0 AND 1),
    excluded_members TEXT NOT NULL DEFAULT '{}',
    ma20_score REAL,
    advancing_score REAL,
    new_high_20_score REAL,
    volume_expansion_score REAL,
    breadth_score REAL CHECK(breadth_score IS NULL OR breadth_score BETWEEN 0 AND 30),
    trend_score REAL CHECK(trend_score IS NULL OR trend_score BETWEEN 0 AND 70),
    total_score REAL CHECK(total_score IS NULL OR total_score BETWEEN 0 AND 100),
    status TEXT NOT NULL CHECK(status IN ('success','insufficient_data','failed')),
    quality_warnings TEXT NOT NULL DEFAULT '[]',
    is_approximate INTEGER NOT NULL CHECK(is_approximate IN (0,1)),
    lookahead_warning TEXT NOT NULL,
    calculation_version TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(classification_system, sector_code, trade_date, calculation_version)
);

CREATE INDEX IF NOT EXISTS idx_sector_breadth_latest
ON sector_breadth_scores(classification_system, sector_code, trade_date DESC);
