CREATE TABLE IF NOT EXISTS backtest_runs (
 run_id TEXT PRIMARY KEY,run_type TEXT NOT NULL DEFAULT 'daily_backtest' CHECK(run_type='daily_backtest'),
 parameters_json TEXT NOT NULL,parameter_hash TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN ('running','success','partial','failed')),
 backtest_version TEXT NOT NULL,backtest_scope TEXT NOT NULL CHECK(backtest_scope='daily_proxy'),detection_version TEXT NOT NULL DEFAULT 'first_limit_v1',
 start_date TEXT,end_date TEXT,data_cutoff_date TEXT NOT NULL,symbols_json TEXT NOT NULL DEFAULT '[]',
 planned_count INTEGER NOT NULL DEFAULT 0 CHECK(planned_count>=0),success_count INTEGER NOT NULL DEFAULT 0 CHECK(success_count>=0),
 unresolved_count INTEGER NOT NULL DEFAULT 0 CHECK(unresolved_count>=0),skipped_count INTEGER NOT NULL DEFAULT 0 CHECK(skipped_count>=0),
 failure_count INTEGER NOT NULL DEFAULT 0 CHECK(failure_count>=0),is_dry_run INTEGER NOT NULL CHECK(is_dry_run IN(0,1)),
 last_error TEXT,started_at TEXT NOT NULL,finished_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS backtest_run_items (
 run_id TEXT NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,item_key TEXT NOT NULL,symbol TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('success','skipped','failed')),trade_count INTEGER NOT NULL DEFAULT 0 CHECK(trade_count>=0),
 closed_count INTEGER NOT NULL DEFAULT 0 CHECK(closed_count>=0),unresolved_count INTEGER NOT NULL DEFAULT 0 CHECK(unresolved_count>=0),
 skipped_count INTEGER NOT NULL DEFAULT 0 CHECK(skipped_count>=0),signal_id INTEGER,result_json TEXT,error_type TEXT,last_error TEXT,
 started_at TEXT NOT NULL,finished_at TEXT,updated_at TEXT NOT NULL,PRIMARY KEY(run_id,item_key),UNIQUE(run_id,symbol));
CREATE TABLE IF NOT EXISTS backtest_signals (id INTEGER PRIMARY KEY AUTOINCREMENT,run_id TEXT NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,event_id INTEGER NOT NULL,observation_id INTEGER NOT NULL,symbol TEXT NOT NULL,first_limit_date TEXT NOT NULL,observation_date TEXT NOT NULL,trading_day_offset INTEGER NOT NULL,detection_version TEXT NOT NULL,scoring_version TEXT NOT NULL,pullback_version TEXT NOT NULL,context_scoring_version TEXT NOT NULL,backtest_version TEXT NOT NULL,daily_base_score NUMERIC,signal_status TEXT NOT NULL,signal_available_at TEXT NOT NULL,approximate_entry INTEGER NOT NULL CHECK(approximate_entry=1),lookahead_check TEXT NOT NULL,reason TEXT,UNIQUE(run_id,event_id));
CREATE TABLE IF NOT EXISTS backtest_trades (id INTEGER PRIMARY KEY AUTOINCREMENT,signal_id INTEGER NOT NULL UNIQUE REFERENCES backtest_signals(id) ON DELETE CASCADE,entry_status TEXT NOT NULL,entry_reason TEXT,actual_entry_date TEXT,entry_price_raw NUMERIC,entry_price NUMERIC,shares INTEGER,entry_cost NUMERIC,exit_signal_date TEXT,original_exit_reason TEXT,exit_order_status TEXT,exit_delay_market_days INTEGER NOT NULL DEFAULT 0,terminal_status TEXT,unresolved_reason TEXT,exit_status TEXT NOT NULL,exit_reason TEXT,actual_exit_date TEXT,exit_price_raw NUMERIC,exit_price NUMERIC,exit_cost NUMERIC,gross_return NUMERIC,net_return NUMERIC,holding_days INTEGER,mfe NUMERIC,mae NUMERIC,intraday_path_ambiguous INTEGER NOT NULL DEFAULT 0,s1_proxy INTEGER NOT NULL DEFAULT 1,minute_path_unavailable INTEGER NOT NULL DEFAULT 1,relative_return NUMERIC,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,CHECK((terminal_status='open_unresolved' AND actual_exit_date IS NULL AND exit_price IS NULL AND gross_return IS NULL AND net_return IS NULL AND unresolved_reason IS NOT NULL) OR (terminal_status<>'open_unresolved' AND unresolved_reason IS NULL)));
CREATE TABLE IF NOT EXISTS backtest_exit_delays (trade_id INTEGER NOT NULL REFERENCES backtest_trades(id) ON DELETE CASCADE,market_date TEXT NOT NULL,delay_market_day_number INTEGER NOT NULL CHECK(delay_market_day_number BETWEEN 1 AND 5),untradable_reason TEXT NOT NULL CHECK(untradable_reason<>''),order_status TEXT NOT NULL CHECK(order_status<>''),created_at TEXT NOT NULL,PRIMARY KEY(trade_id,market_date),UNIQUE(trade_id,delay_market_day_number));
CREATE INDEX IF NOT EXISTS idx_backtest_exit_delays_trade ON backtest_exit_delays(trade_id,delay_market_day_number);
CREATE TABLE IF NOT EXISTS backtest_daily_equity (run_id TEXT NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,trade_date TEXT NOT NULL,equity NUMERIC,benchmark_equity NUMERIC,cash NUMERIC,positions INTEGER,PRIMARY KEY(run_id,trade_date));
CREATE TABLE IF NOT EXISTS backtest_metrics (run_id TEXT NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,scope TEXT NOT NULL,metric_key TEXT NOT NULL,metric_value NUMERIC,details_json TEXT NOT NULL DEFAULT '{}',PRIMARY KEY(run_id,scope,metric_key));
CREATE TABLE IF NOT EXISTS backtest_group_metrics (run_id TEXT NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,group_key TEXT NOT NULL,group_value TEXT NOT NULL,metric_key TEXT NOT NULL,metric_value NUMERIC,PRIMARY KEY(run_id,group_key,group_value,metric_key));
CREATE TABLE IF NOT EXISTS backtest_parameter_results (run_id TEXT NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,parameter_hash TEXT NOT NULL,parameter_json TEXT NOT NULL,is_main INTEGER NOT NULL CHECK(is_main IN(0,1)),is_exploratory INTEGER NOT NULL CHECK(is_exploratory IN(0,1)),metric_json TEXT NOT NULL,PRIMARY KEY(run_id,parameter_hash));
